
params:
    nt: [3, 5]
    a: 0.8744896974945239
    b: 0.7499641699190263
    append_x: False
    append_y: False
    Tmax: 0.001
    Tmin: 0.000001
    alpha: 0.99
    nsteps: 10
    nsteps_per_T: 10000
    cooling: 'exponential'
    alpha: 0.99
    n: 4
    position_delta: 0.002
    angle_delta: 1.
    angle_delta2: 1.
    delta_t: 0.002
    random_state: 42
    log_freq: 5000
